---

- name: install dante
  apt: pkg=dante-server state=installed
  tags: 
   - dante

- name: upload config
  template: src=danted.conf dest=/etc/danted.conf
  notify:
    - restart danted
  tags: 
   - dante

 
