  - name: Stop Ruby Service In RedHat Client
    shell: ps -ef|grep ruby|grep -v grep|awk '{print $2}'|xargs kill -9 >>/dev/null
    ignore_errors: yes
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
  - name: Delete Ruby Install Dir In RedHat Client
    shell: rm -rf {{ ruby_dir}}/ruby-{{ ruby_version }}
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
  - name: Delete Ruby Soft Link Script
    shell: rm -rf /usr/bin/{{ item }}
    with_items:
      - ruby
      - gem
      - bundle
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
