  - name: Delete Ruby Install Dir In RedHat Client
    shell: rm -rf {{ ruby_dir}}/ruby-{{ ruby_version }}
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
  - name: Delete Ruby Soft Link Script
    shell: rm -rf /usr/bin/{{ item }}
    with_items:
      - ruby
      - gem
      - bundle
    ignore_errors: yes
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
  - name: Recovery Old Ruby Soft Link Script
    shell: mv -f /usr/bin/{{ item }}_back /usr/bin/{{ item }}
    with_items:
      - ruby
      - gem
      - bundle
    ignore_errors: yes
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
