  - name: Copy Ruby Software To Redhat Client
    copy: src=ruby-{{ ruby_version }}.tar.gz dest=/tmp/ruby-{{ ruby_version }}.tar.gz owner=root group=root
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
  - name: Uncompression Ruby Software To Redhat Client
    shell: tar zxf /tmp/ruby-{{ ruby_version }}.tar.gz -C {{ ruby_dir }}
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
  - name: Copy Redis Config To Redhat Client
    shell: ln -s {{ ruby_dir }}/ruby-{{ ruby_version }}/bin/{{ item }} /usr/bin/{{ item }}
    with_items:
      - ruby
      - gem
      - bundle
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
