---
# Packages
#
- name: Ensure aptitude is installed
  apt: name=aptitude state=present

- name: Update APT Package cache
  apt: update_cache=yes cache_valid_time=3600
  changed_when: false

- name: Upgrade APT to the latest packages
  apt: upgrade=safe

- name: Install required packages
  apt: state=installed pkg={{ item }}
  with_items: "{{ required_packages }}"

- name: Install optional packages
  apt: state=installed pkg={{ item }}
  with_items: "{{ optional_packages }}"

- name: Adjust APT update intervals
  copy: src=files/apt_periodic dest=/etc/apt/apt.conf.d/10periodic

- name: Fix blocktype for default ufw action to be deny
  copy: src=files/ufw.local dest=/etc/fail2ban/action.d/ufw.local
  notify:
  - Restart fail2ban
