---
- hosts: apnp-backend

  roles:
    - common

    - role: ss-server
      vars:
        name: "default"
        port: "{{ shadowsocks_servers.default.port }}"
        password: "{{ shadowsocks_servers.default.password }}"
        enalbe_udp: "{{ shadowsocks_servers.default.enable_udp }}"

    - role: squid-root

