---
- hosts: shadowsocks-multiport

  roles:
    - common

    - role: ss-server
      vars:
        name: "multiport"
        port_password: "{{ shadowsocks_servers.multiport.port_password }}"
        enable_udp: "{{ shadowsocks_servers.multiport.enable_udp }}"
        shadowsocks_provider: "python"
        shadowsocks_enable_multiport: true

