galaxy_info:
  author: Deng Lei
  description: Delete Redis Slave
  license: MIT
  min_ansible_version: 1.6
  platforms:
  - name: CentOS
    versions:
    - 6
  categories:
  - Service
dependencies: []
