    - name: "创建kube目录"
      file:
         path: "/root/.kube"
         state: directory
    - name: "拷贝kubeconfig文件"
      template:
         src: "kubelet.kubeconfig.j2"
         dest: "/root/.kube/config"
    - name: "安装kubectl"
      get_url:
         url: "{{ download_url }}/k8s/{{ k8s_version }}/kubectl"
         dest: /usr/bin/
      tags: install_kubectl
    - name: "添加执行权限"
      file:
         dest: "/usr/bin/kubectl"
         mode: 0755
      tags: install_kubectl
