  - name: Delete Apache compression Software In Redhat Client
    shell: rm -rf /tmp/httpd-{{ apache_version }}.tar.gz /tmp/libiconv.tar.gz
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
