---
- name: create folder that sotre secrets
  file: path=/etc/openvpn/.secret/ state=directory
  tags:
    - openvpn

- name: gen secret
  shell: openvpn --genkey --secret /etc/openvpn/.secret/{{ openvpn_name }}.key
         creates=/etc/openvpn/.secret/{{ openvpn_name }}.key
  tags:
    - openvpn

- name: get secret content
  shell: cat /etc/openvpn/.secret/{{ openvpn_name }}.key
  register: secret_content_action
  tags:
    - openvpn

