---

- include: gen_cert_client.yml
  when: openvpn_cert_source == "gen"

- name: gen client conf  (tls mode) (to local file)
  local_action: template src="tls-client.conf" dest={{ openvpn_client_conf_file }}
  sudo: no

