---

- name: restart shrpx
  supervisorctl: name=shrpx state=restarted
  tags:
    - spdy-proxy


- name: restart node-spdyproxy
  supervisorctl: name=node-spdyproxy state=restarted
  tags:
    - spdy-proxy
    - node-spdyproxy

