---
#vpn server management api

- name: install header file
  apt: pkg=python-dev state=present

- name: ensure directory used by vpn-mgr exists
  file: path={{ item }} state=directory
  with_items:
    - /opt/vpnmgr-agent
    - /opt/vpnmgr-agent/env
  tags: 
    - vpnmgr-agent

- name: install some vpn-mgr dependecy
  pip: name="git+https://github.com/ftao/python-ifcfg.git#egg=ifcfg" virtualenv=/opt/vpnmgr-agent/env virtualenv_site_packages=yes extra_args="-e"
  notify:
    - restart vpnmgr-agent
  tags: 
    - vpnmgr-agent

- name: install vpn-mgr
  pip: name="git+https://github.com/ftao/vpn-mgr#egg=vpn-mgr" virtualenv=/opt/vpnmgr-agent/env virtualenv_site_packages=yes extra_args="-e"
  notify:
    - restart vpnmgr-agent
  tags: 
    - vpnmgr-agent

- name: setup supervisor config
  template: src=vpn-mgr.supervisor.conf dest=/etc/supervisor/conf.d/vpnmgr-agent.conf
  notify:
    - restart vpnmgr-agent
  tags: 
    - vpnmgr-agent
