- name: find xenial image
  hosts: localhost
  gather_facts: False
  tasks:
    - name: find the image
      ec2_ami_find:
        name: "ubuntu/images/ebs-ssd/ubuntu-xenial-16.04-amd64-server-*"
        sort: name
        sort_order: descending
        sort_end: 1
        no_result_action: fail
      register: ami
    - name: output image info
      debug: var=ami

