---

- name: Install repo for Debian
  include: repo.debian.yml
  when: ansible_os_family == "Debian"

- name: Install repo for RedHat
  include: repo.redhat.yml
  when: ansible_os_family == "RedHat"
