---
- hosts: localhost
  tasks:
  - debug:
      msg: Testing a binary module written in Rust
  
  - debug:
      var: ansible_system
  
  - name: ping
    ping:
  
  - name: Hello, World!
    action: rust_helloworld
    register: hello_world
  
  - assert:
      that:
      - >
          hello_world.msg == "Hello, World!"
  
  - name: Hello, Ansible!
    action: rust_helloworld
    args:
      name: Ansible
    register: hello_ansible
  
  - assert:
      that:
      - >
          hello_ansible.msg == "Hello, Ansible!"
  
  - name: Async Hello, World!
    action: rust_helloworld
    async: 10
    poll: 1
    register: async_hello_world
  
  - assert:
      that:
      - >
          async_hello_world.msg == "Hello, World!"
  
  - name: Async Hello, Ansible!
    action: rust_helloworld
    args:
      name: Ansible
    async: 10
    poll: 1
    register: async_hello_ansible
  
  - assert:
      that:
      - >
          async_hello_ansible.msg == "Hello, Ansible!"
