---
# Main task list for Base

- include: packages-repo-setup.yml
- include: harden-basic.yml
- include: packages-system.yml
- include: packages-security.yml
- include: packages-editors.yml
- include: packages-networking.yml
