  - name: Create Mysql Install Dir
    file: dest={{ mysql_dir }} state=directory
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
  - name: Uncompression Mysql Software To Redhat Client
    shell: tar zxf /tmp/mysql.tar.gz -C {{ mysql_dir }}
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
  - name: Modify Mysql Dir Permission In Redhat Client
    file: path={{ item }} owner={{ mysql_user }} group={{ mysql_user }} mode=0755
    with_items:
      - "{{ mysql_datadir }}"
      - "{{ mysql_basedir }}"
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
  - name: Install Mysql Script In Redhat Client
    shell: /bin/bash /tmp/install_mysql.sh
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
  - name: Wait Untils Mysql Service Avaiable In Redhat Client
    shell: "{{ mysql_basedir }}/bin/mysql -h localhost -u {{ mysql_database_user }} -P {{ mysql_port }} -S {{ mysql_sock }} -e 'show databases;' && echo 'ok' || echo 'work'"
    register: result
    until: result.stdout.find("ok") != -1
    retries: 20
    delay: 5
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6 
  - name: Start Myql Security Script In Redhat Client
    shell: "/bin/bash /tmp/mysql_security.sh && echo 'ok' || echo 'work'"
    register: run_result
    until: run_result.stdout.find("ok") != -1
    retries: 10
    delay: 5
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
  - name: Add Boot Start Mysql Service In Redhat Client
    shell: chkconfig --level 345 mysqld on
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
  - name: Copy Mysql Create Slave Script To Redhat Client
    template: src=create_master_slave.sh dest=/tmp/ owner=root group=root mode=0755
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
  - name: Create Mysql Master And Slave  In redhat Client
    shell: /bin/bash /tmp/create_master_slave.sh
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
  - name: Delete Create Mysql Master And Slave Script  In redhat Client
    shell: rm -rf  /tmp/create_master_slave.sh
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
