    - name: "安装haproxy"
      yum:
         name: haproxy
         state: present
    - name: "拷贝haproxy.cfg文件"
      template:
         src: "haproxy.cfg.j2"
         dest: "/etc/haproxy/haproxy.cfg"
    - name: "启动haproxy"
      systemd:
         name: haproxy
         enabled: yes
         daemon_reload: yes
         state: started
