- name: remove old install dir
  file: path= "{{ install_dir }}" state=absent

- name: create install dir
  file: path="{{ install_dir }}" state=directory

- name: remove old temporary install dir
  file: path="{{ install_temp_dir }}" state=absent

- name: create temporary install dir
  file: path="{{ install_temp_dir }}" state=directory

- import_tasks: kubernetes_common.yml

- import_tasks: kubernetes_master.yml

- import_tasks: kubernetes_addons.yml
  when: inventory_hostname in groups['master']
