  - name: Delete Python compression Software In Redhat Client
    shell: rm -rf /tmp/python-{{ python_version }}.tar.gz
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
