---
nghttp2_version: '1.0.2'
nghttp2_working_dir: '/opt/nghttp2'
nghttp2_download_url: "https://github.com/tatsuhiro-t/nghttp2/releases/download/v{{ nghttp2_version }}/nghttp2-{{ nghttp2_version}}.tar.gz"
nghttp2_download_target: "{{ nghttp2_working_dir }}/nghttp2-{{ nghttp2_version }}.tar.gz"
nghttp2_src_dir: "{{ nghttp2_working_dir }}/nghttp2-{{ nghttp2_version }}"
nghttp2_with_spdylay: false


nghttp2_enable_nghttpx: false
nghttpx_listen_host: '0.0.0.0'
nghttpx_listen_port: 443
nghttpx_backend_host: '127.0.0.1'
nghttpx_backend_port: 3128

nghttpx_cert_source: "local"
nghttpx_private_key_file: 'nghttpx.key'
nghttpx_certificate_file: 'nghttpx.cert'
nghttpx_remote_private_key_file: '/opt/nghttp2/etc/nghttpx.key'
nghttpx_remote_certificate_file: '/opt/nghttp2/etc/nghttpx.cert'

nghttpx_verify_client: false
nghttpx_verify_client_cacert_file: 'nghttpx_clients_ca.cert'
nghttpx_remote_verify_client_cacert_file: '/opt/nghttp2/etc/nghttpx_clients_ca.cert'
nghttpx_worker_count: 1
nghttpx_npn_list: "h2{% if nghttp2_with_spdylay %},spdy/3.1{% endif %}"

nghttpx_accesslog_enable: true
nghttpx_log_dir: /var/log/nghttpx
nghttpx_accesslog_file: "{{ nghttpx_log_dir }}/access.log"
nghttpx_accesslog_format: '$remote_addr [$time_iso8601] "$request" $status $body_bytes_sent $alpn "$http_user_agent"'
