---
- name: Add backports repository for Deiban
  apt_repository: repo='deb http://ftp.debian.org/debian {{ansible_distribution_release}}-backports main contrib non-free' state=present update_cache=yes
  when: ansible_distribution == "Debian"

- name: install libgnutls28-dev
  apt: pkg={{ item }} default_release="{{ansible_distribution_release}}-backports"
  with_items:
    - libgnutls28-dev 

- name: install some depdency
  apt: pkg={{ item }} state=installed
  with_items:
    - build-essential
    - libwrap0-dev 
    - libpam0g-dev 
    - libdbus-1-dev
    - libreadline-dev 
    - libnl-route-3-dev 
    - libprotobuf-c0-dev 
    - libpcl1-dev 
    - libopts25-dev
    - autogen 
    - libseccomp-dev 
#    - libhttp-parser-dev
    - gnutls-bin
