---
# Aminator playbook for ubuntu
- name: Aminator
  user: ubuntu
  sudo: True
  tags: aminator
  hosts: all
  roles:
    - base
    - aminator
  vars_files:
    - vars/{{ ansible_distribution }}.yml
