---
# Edda playbook for Amazon Linux
- name: Edda
  user: ec2-user
  sudo: True
  tags: edda
  hosts: all
  roles:
    - base
    - tomcat
    - mongodb
    - edda
  vars:
    local_war: "" 
  vars_files:
    - vars/{{ ansible_distribution }}.yml
  
