---
# Eureka playbook for ubuntu
- name: Eureka
  user: ubuntu
  sudo: True
  tags: eureka
  hosts: all
  roles:
    - base
    - tomcat
    - eureka
  vars:
    local_war: "" 
    tomcat_extra_opts: "-Darchaius.deployment.applicationId=eureka -Deureka.datacenter=cloud"
  vars_files:
    - vars/{{ ansible_distribution }}.yml
