---
- hosts: "{{host}}"
  remote_user: "{{user}}"
  gather_facts: True
  roles:
    - common
    - mysql_install
    - mysql_tpcc_install
    - sysbench_install
    - fio_install
    - complete_testing_install
