---
- include_tasks: tarball.yml

- include_tasks: upstart.yml
  when: not zookeeper_debian_systemd_enabled
  tags: deploy

- include_tasks: systemd.yml
  when: zookeeper_debian_systemd_enabled
  tags: deploy
