#mysql stuff

- name: install mysql-server
  apt: pkg=mysql-server state=installed
  tags: mysql 

- name: install python-mysqldb
  apt: pkg=python-mysqldb state=installed
  tags: mysql 

- name: start mysql
  service: name=mysql state=started
  tags: mysql 

- name: ensure mysql root password 
  mysql_user: name=root host=localhost password="{{ mysql_root_password }}" state=present
  tags: mysql

- name: install .my.cnf
  template: src=HOME/.my.cnf  dest=~/.my.cnf mode=600
  tags: mysql
