---
- name: Adding dummy0 interface if it doesn't exist & Add the master_ip to dummy0 and up the interface if it's down
  shell: "{{ item }}"
  with_items:
    - "ip link add dummy0 type dummy"
    - "ip address add {{ master_ip }}/32 dev dummy0"
    - "ip link set dummy0 up"
  ignore_errors: True

- name: Install Python yaml for k8s
  apt:
    name: python-yaml

- name: daemon_reload
  systemd: 
    daemon_reload: yes

- name: Start services
  service: 
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler

#- name: RBAC for kubelets - CLusterRole
#  kubernetes:
#    api_endpoint: "{{ master_ip }}"
#    insecure: true
#    file_reference: "{{ role_path }}/files/rbac_clusterRole.yaml"
#    state: present


#- name: RBAC for kubelets - ClusterRoleBinding
#  kubernetes:
#    api_endpoint: "{{ master_ip }}"
#    insecure: true
#    file_reference: "{{ role_path }}/files/rbac_clusterRoleBinding.yaml"
#    state: present

#- name: RBAC for kubelets - ClusterRole
#  shell: "kubectl apply -f /tmp/rbac_clusterRole.yaml"

#- name: RBAC for kubelets - ClusterRoleBinding
#  shell: "kubectl apply -f /tmp/rbac_clusterRoleBinding.yaml"