---
#install shadowsocks

- name: increase fileno
  lineinfile: dest=/etc/security/limits.conf line="{{item}}" insertbefore="# End of file" state=present
  with_items:
    - "* soft nofile 51200"
    - "* hard nofile 51200"
  notify:
    - reload supervisor
  tags:
    - ss-server

- name: add ulimit in defaults/supervisor
  lineinfile: dest=/etc/default/supervisor line="ulimit -n 51200" state=present
  notify:
    - reload supervisor
  tags:
    - ss-server

# see https://github.com/clowwindy/shadowsocks/wiki/Optimizing-Shadowsocks
- name: update sysctl for performance
  sysctl: name="{{ item.name }}" value="{{ item.value }}" state=present reload=yes
  with_items:
    - {"name" : "fs.file-max", "value" : "51200"}
    - {"name" : "net.core.rmem_max", "value" : "67108864 "}
    - {"name" : "net.core.wmem_max", "value" : "67108864 "}
    - {"name" : "net.core.netdev_max_backlog", "value" : "250000"}
    - {"name" : "net.core.somaxconn", "value" : "3240000"}
  when: shadowsocks_tune_system

- name: update tcp config  for performance
  sysctl: name="{{ item.name }}" value="{{ item.value }}" state=present reload=yes
  with_items:
    - {"name" : "net.ipv4.tcp_syncookies", "value" : "1"}
    - {"name" : "net.ipv4.tcp_tw_reuse", "value" : "1"}
    - {"name" : "net.ipv4.tcp_tw_recycle", "value" : "0"}
    - {"name" : "net.ipv4.tcp_fin_timeout", "value" : "30"}
    - {"name" : "net.ipv4.tcp_keepalive_time", "value" : "1200"}
    - {"name" : "net.ipv4.ip_local_port_range", "value" : "10000 65000"}
    - {"name" : "net.ipv4.tcp_max_syn_backlog", "value" : "8192"}
    - {"name" : "net.ipv4.tcp_max_tw_buckets", "value" : "5000"}
    - {"name" : "net.ipv4.tcp_fastopen", "value" : "3"}
    - {"name" : "net.ipv4.tcp_rmem", "value" : "4096 87380 67108864"}
    - {"name" : "net.ipv4.tcp_wmem", "value" : "4096 65536 67108864"}
    - {"name" : "net.ipv4.tcp_mtu_probing", "value" : "1"}
  when: shadowsocks_tune_system and shadowsocks_tune_tcp
  tags:
    - ss-server

- name: change tcp_congestion_control protocol
  sysctl: name="{{ item.name }}" value="{{ item.value }}" state=present reload=yes
  with_items:
    - {"name" : "net.ipv4.tcp_congestion_control", "value" : "hybla"}
  when: shadowsocks_change_tcp_congestion_control
  tags:
    - ss-server

- name: ensure working dir exists
  action: file path=/opt/ss-server/ state=directory
  tags:
    - ss-server

- include: install_libev.yml
  when: shadowsocks_provider == "libev"

- include: install_python.yml
  when: shadowsocks_provider == "python"

- include: install_go.yml
  when: shadowsocks_provider == "go"

- name: install shadowssocks-server supervisorconfig
  template: src=ss-server.supervisor.conf
            dest=/etc/supervisor/conf.d/ss-server-{{ name }}.conf

  notify:
    - "restart shadowsocks-server {{ name }}"
  tags:
    - ss-server

- name: install shadowssocks server config file
  template: src=config.json
            dest=/opt/ss-server/config-{{ name }}.json
            mode=640
  notify:
    - "restart shadowsocks-server {{ name }}"
  tags:
    - ss-server

- name: make shadowssocks-server is present 
  supervisorctl: name=ss-server-{{ name }} state=present
