complete_testing_temp_dir: /tmp/complete_testing_temp
complete_testing_dir: /tmp/complete_testing
tpcc_dir: /tmp/tpcc_log
mysql_database_user: root
mysql_passwd: 'E4yR3WnoluSFTCBAI'
mysql_port: 3306
mysql_sock: /data/mysql/datadir/mysql.sock
tpcc_database_name: tpcc100
warehouse: 50
w: 50
c: 50
r: 30
l: 300
f: 'tpcc-mysql'
sysbench_dir: /tmp/sysbench_log
cpu_max_prime: 20000
num_threads: 64
mutex_loops: 5000
mutex_locks: 1000000
mutex_num: 2048
memory_total_size: 8G
memory_block_size: 8K

fio_dir: /tmp/fio_log
fio_version: 2.1.11
filename: random_write_read
direct: 1
iodepth: 1
rw: randrw
rwmixread: 70
ioengine: psync
bs: 16K
size: 2G
numjobs: 30
runtime: 1000
name: random_read_write
ioscheduler: noop
