---
listen_port: 6128

nameservers:
  - 127.0.0.1

cache_peers:
  - name: cp1
    host: 127.0.0.1
    port: 6129

domain_groups:
  #order is important
  - name: cn
    ip_list_file: cn_ips.txt
    is_direct: true

  - name: blocked
    peers:
      - cp1
    is_direct: false
    is_others: true
